version: "3.8"

services:
  editor:
    build:
      context: .
      target: dev
    ports:
      - "9439:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npx rollup -c --watch
